version: "3.7"
services:
  oengus_bot:
    container_name: oengus-discord-bot
    build:
      context: .
    environment:
      - BOT_TOKEN=
      - COMMAND_GUILD_ID=
      - REMOVE_COMMANDS_ON_EXIT=false
